export interface RemoteUsage { imageCount: number; byteCount: number }
export interface RemoteImageAsset { id: string; archiveId: string; promptRecordId?:string; url: string; pathname: string; contentType: string; byteSize: number; width?: number; height?: number; provider: string; modelId: string; createdAt: string; expiresAt: string }
export interface RemotePromptRecord { id: string; prompt: string; promptZh?:string; snapshot?:Record<string,unknown>; negativePrompt: string; provider: string; modelId: string; createdAt: string }
export interface RemoteArchiveSummary { id: string; name: string; summary: string; profile?:Record<string,unknown>; category?:string; worldId?:string; worldName?:string; tags?:string[]; relatedIds?:string[]; updatedAt?:string; promptCount?:number; imageCount: number; byteCount: number; coverUrl?: string; nearestExpiry?: string }
export interface RemoteArchiveDetail { archive: RemoteArchiveSummary & { profile: Record<string, unknown> }; prompts: RemotePromptRecord[]; images: RemoteImageAsset[] }
export interface ContentWorld { id:string;name:string;profile:Record<string,unknown>;updatedAt?:string }
export function getWorkspaceId(storage?: Storage, createId?: () => string): string
export function assetErrorMessage(code?: string, fallback?: string): string
export function createAssetApi(options?: { workspaceId?: string; fetchImpl?: typeof fetch }): { workspaceId: string; listWorlds():Promise<ContentWorld[]>;getWorld(id:string):Promise<ContentWorld>;saveWorld(world:ContentWorld):Promise<ContentWorld>;deleteWorld(id:string):Promise<{deleted:boolean;detachedCharacterCount:number}>;updateArchiveMetadata(id:string,patch:Record<string,unknown>):Promise<unknown>;listRemoteAssets(): Promise<{ archives: RemoteArchiveSummary[]; worlds:ContentWorld[]; usage: RemoteUsage }>; getRemoteArchive(id: string): Promise<RemoteArchiveDetail>; saveRemoteImage(input: Record<string, unknown>): Promise<{ asset: RemoteImageAsset; usage: RemoteUsage; nearLimit: boolean }>; saveRemoteArchive(input: Record<string, unknown>): Promise<{ archive: RemoteArchiveSummary }>; deleteRemoteArchive(id: string): Promise<{ deleted: boolean }>; deleteRemoteImage(id: string): Promise<{ deleted: boolean }>; getRemoteImageDownloadUrl(id: string): string }
