import { useState } from 'react'
import type { RemoteArchiveDetail, RemoteImageAsset } from '../agent/assetApi.mjs'

type Tab = 'info' | 'prompts' | 'images'
export function ArchiveDetailView({ archive, onBack, onOpenImage, onDeleteImage, deleting }: { deleting: boolean; archive: RemoteArchiveDetail; onBack: () => void; onOpenImage: (image: RemoteImageAsset) => void; onDeleteImage: (image: RemoteImageAsset) => void }) {
  const initial = new URLSearchParams(location.search).get('tab') as Tab | null
  const [tab, setTab] = useState<Tab>(['info', 'prompts', 'images'].includes(initial || '') ? initial! : 'info')
  const changeTab = (next: Tab) => { setTab(next); const url = new URL(location.href); url.searchParams.set('tab', next); history.replaceState(null, '', url) }
  const profile = archive.archive.profile || {}
  return <><section className="hero-card creation-hero"><div><div className="panel-label">ASSET ARCHIVE</div><h2>{archive.archive.name}</h2><p>{archive.archive.summary}</p></div><button className="choice" type="button" onClick={onBack}>返回资产库</button></section><nav className="archive-tabs" aria-label="档案内容">{([['info', '档案信息'], ['prompts', 'Prompt 记录'], ['images', '档案图片']] as const).map(([id, label]) => <button key={id} type="button" className={tab === id ? 'is-active' : ''} onClick={() => changeTab(id)}>{label}</button>)}</nav>{tab === 'info' && <section className="panel archive-detail"><h3>角色档案</h3><div className="npc-grid">{Object.entries(profile).map(([key, value]) => <div className={typeof value === 'string' && value.length > 80 ? 'full-field' : ''} key={key}><span className="field-label">{key}</span><p>{Array.isArray(value) ? value.join('、') : typeof value === 'object' ? JSON.stringify(value) : String(value ?? '')}</p></div>)}</div></section>}{tab === 'prompts' && <section className="panel prompt-history"><h3>Prompt 记录</h3>{archive.prompts.length === 0 ? <p className="section-hint">还没有关联的 Prompt。</p> : archive.prompts.map((prompt) => <details key={prompt.id}><summary><strong>{prompt.modelId}</strong><span>{new Date(prompt.createdAt).toLocaleString('zh-CN')}</span></summary><div className="npc-grid"><div className="full-field"><span className="field-label">生成提示词</span><p>{prompt.prompt}</p></div><div className="full-field"><span className="field-label">反向提示词</span><p>{prompt.negativePrompt || '无'}</p></div><div><span className="field-label">Provider</span><p>{prompt.provider}</p></div><div><span className="field-label">Model ID</span><p>{prompt.modelId}</p></div></div></details>)}</section>}{tab === 'images' && <section className="panel"><h3>档案图片</h3>{archive.images.length === 0 ? <p className="section-hint">还没有保存图片。</p> : <div className="archive-image-grid">{archive.images.map((image) => <article className="archive-image" key={image.id}><button type="button" onClick={() => onOpenImage(image)}><img src={image.url} alt={archive.archive.name} /></button><p>{image.modelId}</p><small>{new Date(image.expiresAt).toLocaleDateString('zh-CN')} 到期</small><button className="choice asset-delete" type="button" disabled={deleting} onClick={() => onDeleteImage(image)}>{deleting ? '处理中…' : '删除图片'}</button></article>)}</div>}</section>}</>
}
