import {designSections} from '../content/detailSections.mjs'
import {createStudioHandoff} from '../content/studioHandoff.mjs'
import type {StudioHandoff} from '../content/studioHandoff.mjs'
import { useState } from 'react'
import { contentCategories, categoryLabel } from '../content/categories.mjs'
import type { ContentWorld, RemoteArchiveDetail, RemoteArchiveSummary, createAssetApi } from '../agent/assetApi.mjs'
import { ImageViewer } from './ImageViewer'

type Props={onUseForImage?:(handoff:StudioHandoff)=>void;detail:RemoteArchiveDetail;worlds:ContentWorld[];archives:RemoteArchiveSummary[];api:ReturnType<typeof createAssetApi>;onBack:()=>void;onReload:()=>Promise<void>;onResume:(detail:RemoteArchiveDetail,promptId?:string)=>void}
export function ContentItemDetail({detail,worlds,archives,api,onBack,onReload,onResume,onUseForImage}:Props) {
 const [tab,setTab]=useState<'design'|'prompts'|'images'>('design')
 const [editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const [name,setName]=useState(detail.archive.name),[category,setCategory]=useState(detail.archive.category || 'unknown')
 const [worldId,setWorldId]=useState(String(detail.archive.worldId || detail.archive.profile.worldId || '')),[tags,setTags]=useState((detail.archive.tags || []).join('，'))
 const [related,setRelated]=useState<string[]>(detail.archive.relatedIds || [])
 const [viewer,setViewer]=useState<RemoteArchiveDetail['images'][number]|null>(null)
 const run=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();await onReload()}catch(e){setError(e instanceof Error?e.message:'操作失败')}finally{setBusy(false)}}
 const deleteItem=async()=>{setBusy(true);setError('');try{await api.deleteRemoteArchive(detail.archive.id);onBack()}catch(e){setError(e instanceof Error?e.message:'操作失败');setBusy(false)}}
 return <section className="panel content-editor"><div className="content-toolbar"><button className="choice" onClick={onBack}>返回资产库</button><button className="primary-button" onClick={()=>onResume(detail)}>继续设计</button><button className="choice" onClick={()=>setEditing(!editing)}>管理档案</button></div>
 <h2>{detail.archive.name}</h2><p>{categoryLabel(detail.archive.category || '')} · {worlds.find(w=>w.id===(detail.archive.worldId || detail.archive.profile.worldId))?.name || ((detail.archive.worldId || detail.archive.profile.worldId)?'原关联世界暂不可用':'暂不关联世界')}</p><p>{detail.archive.summary}</p>{detail.archive.profile.needsClassification===true && <p>旧版混合档案：历史记录保留原关联，请检查类别与归属。</p>}
 {error && <p role="alert" className="error-message">{error}</p>}
 {editing && <div><label>名称<input value={name} onChange={e=>setName(e.target.value)}/></label><label>类别<select value={category} onChange={e=>setCategory(e.target.value)}><option value="unknown">待分类</option>{Object.entries(contentCategories).map(([id,c])=><option key={id} value={id}>{c.label}</option>)}</select></label><label>所属世界<select value={worldId} onChange={e=>setWorldId(e.target.value)}><option value="">暂不关联世界</option>{worldId&&!worlds.some(w=>w.id===worldId)&&<option value={worldId}>原关联世界暂不可用</option>}{worlds.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>标签<input value={tags} onChange={e=>setTags(e.target.value)}/></label><label>关联条目<select multiple value={related} onChange={e=>setRelated(Array.from(e.target.selectedOptions,o=>o.value))}>{archives.filter(a=>a.id!==detail.archive.id).map(a=><option key={a.id} value={a.id}>{categoryLabel(a.category || '')} · {a.name}</option>)}</select></label><button disabled={busy || !name.trim()} className="primary-button" onClick={()=>void run(async()=>{await api.updateArchiveMetadata(detail.archive.id,{name,category,worldId,tags:tags.split(/[,，]/).map(t=>t.trim()).filter(Boolean),relatedIds:related});setEditing(false)})}>保存修改</button></div>}
 <div className="archive-tabs">{([['design','设计资料'],['prompts',`Prompt 版本 · ${detail.prompts.length}`],['images',`图片 · ${detail.images.length}`]] as const).map(([id,label])=><button key={id} className={`choice ${tab===id?'is-active':''}`} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='design'&&<><h3>设计资料</h3>{detail.archive.profile.visualBrief?<p>{String(detail.archive.profile.visualBrief)}</p>:null}<dl>{designSections(detail.archive).map(row=><div key={row.key}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl>{!designSections(detail.archive).length&&<p>旧记录未保存设计资料，可以使用已有提示词继续创作。</p>}<details><summary>对话来源</summary>{((detail.archive.profile.conversation as {messages?:{role:string;content:string}[]})?.messages || []).map((m,i)=><p key={i}>{m.role==='user'?'你':'AI'}：{m.content}</p>)}</details></>}
 {!!detail.archive.relatedIds?.length && <p>关联：{detail.archive.relatedIds.map(id=>archives.find(a=>a.id===id)?.name || '已移除的条目').join('、')}</p>}
 {tab==='prompts'&&<><h3>Prompt 历史 · {detail.prompts.length}</h3>{detail.prompts.map((prompt,index)=><details key={prompt.id}><summary>记录 {detail.prompts.length-index} · {prompt.createdAt?new Date(prompt.createdAt).toLocaleString('zh-CN'):'过往记录'} · {prompt.modelId}</summary>{prompt.promptZh && <p>{prompt.promptZh}</p>}<p className="preserve-text">{prompt.prompt}</p><p>反向提示词：{prompt.negativePrompt || '无'}</p>{prompt.snapshot?.design!=null && <details><summary>生成时的设计快照</summary><pre>{JSON.stringify(prompt.snapshot.design,null,2)}</pre></details>}<button className="choice" onClick={()=>onResume(detail,prompt.id)}>编辑此 Prompt</button><button className="primary-button" onClick={()=>onUseForImage?.(createStudioHandoff({prompt:prompt.prompt,negativePrompt:prompt.negativePrompt,source:{...prompt.snapshot,name:detail.archive.name,itemId:detail.archive.id,archiveSaved:true},target:detail.archive}))}>一键用于文生图</button></details>)}
 </>}
 {tab==='images'&&<><h3>图片历史 · {detail.images.length}</h3><p>图片临时保留 30 天，设计和 Prompt 记录继续保留。</p><div className="archive-image-grid">{detail.images.map(image=><article key={image.id}><button className="content-image-button" onClick={()=>setViewer(image)}><img className="generated-image" src={image.url} alt={detail.archive.name}/></button><small>{image.modelId} · {new Date(image.expiresAt).toLocaleDateString('zh-CN')} 到期</small><details><summary>本图使用的 Prompt</summary><p className="preserve-text">{detail.prompts.find(p=>p.id===image.promptRecordId)?.prompt || '旧记录未关联 Prompt'}</p></details><button className="choice" disabled={busy} onClick={()=>{if(window.confirm('删除这张图片？设计与 Prompt 会保留。'))void run(()=>api.deleteRemoteImage(image.id))}}>删除图片</button></article>)}</div>
 </>}
 <button className="choice asset-delete" disabled={busy} onClick={()=>{if(window.confirm(`删除“${detail.archive.name}”的设计、${detail.prompts.length} 条 Prompt 和 ${detail.images.length} 张图片？`))void deleteItem()}}>删除整个条目</button>
 {viewer && <ImageViewer image={{url:viewer.url,alt:detail.archive.name,meta:viewer.modelId}} downloadUrl={api.getRemoteImageDownloadUrl(viewer.id)} onClose={()=>setViewer(null)}/>}
 </section>
}
