import {useState} from 'react'
import type {ContentWorld,RemoteArchiveSummary,createAssetApi} from '../agent/assetApi.mjs'
import {designSections} from '../content/detailSections.mjs'
import {libraryCategoryLabel} from '../content/categories.mjs'
type Props={world:ContentWorld;archives:RemoteArchiveSummary[];api:ReturnType<typeof createAssetApi>;onBack:()=>void;onContinue:()=>void;onOpen:(id:string)=>void;onReload:()=>Promise<void>}
export function WorldArchiveDetail({world,archives,api,onBack,onContinue,onOpen,onReload}:Props){
 const [name,setName]=useState(world.name),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const related=archives.filter(a=>(a.worldId || a.profile?.worldId)===world.id)
 return <section className="panel archive-detail"><div className="archive-actions"><button className="choice" onClick={onBack}>返回档案</button><button className="primary-button" onClick={onContinue}>继续设计</button></div><h2>{world.name}</h2><p>世界观 · 已保存</p>{error&&<p role="alert">{error}</p>}<h3>设计资料</h3><dl>{designSections({category:'world',profile:world.profile}).map(row=><div key={row.key}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl><details><summary>对话来源</summary>{((world.profile.conversation as {messages?:{role:string;content:string}[]})?.messages || []).map((m,i)=><p key={i}>{m.role==='user'?'你':'AI'}：{m.content}</p>)}</details><h3>关联内容 · {related.length}</h3><div className="archive-actions">{related.map(a=><button key={a.id} className="choice" onClick={()=>onOpen(a.id)}>{libraryCategoryLabel(a.category || '')} · {a.name}</button>)}</div><details className="advanced-details"><summary>管理档案</summary><label>世界名称<input value={name} onChange={e=>setName(e.target.value)}/></label><button className="choice" disabled={busy || !name.trim()} onClick={async()=>{setBusy(true);try{await api.saveWorld({...world,name,profile:{...world.profile,name}});await onReload()}catch(e){setError(e instanceof Error?e.message:'保存失败')}finally{setBusy(false)}}}>保存名称</button><button className="choice asset-delete" disabled={busy} onClick={async()=>{if(!window.confirm('删除此世界档案？关联内容保留并解除世界关联。'))return;setBusy(true);try{await api.deleteWorld(world.id);onBack()}catch(e){setError(e instanceof Error?e.message:'删除失败')}finally{setBusy(false)}}}>删除世界档案</button></details></section>
}
